[package]
name = "aruna-sparql"
version = "0.1.0"
edition = "2024"

[dependencies]
aruna-core = { workspace = true }
aruna-rdf-store = { workspace = true }
aruna-search = { workspace = true }
oxrdf = { workspace = true }
spargebra = { workspace = true }
spareval = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
