[package]
name = "aruna-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
aruna-core = { workspace = true }
aruna-rdf-store = { workspace = true }
aruna-repl = { workspace = true }
aruna-search = { workspace = true }
aruna-sparql = { workspace = true }
aruna-shacl = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
