[package]
name = "aruna-rocrate"
version = "0.1.0"
edition = "2024"

[dependencies]
aruna-core = { workspace = true }
aruna-repl = { workspace = true }
aruna-rdf-store = { workspace = true }
oxrdf = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }
rocraters = { workspace = true }

[dev-dependencies]
aruna-sync = { workspace = true }
criterion = "0.5"
tempfile = { workspace = true }

[[bench]]
name = "partial_loading"
harness = false
