[package]
name = "aruna-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
aruna-core = { workspace = true }
aruna-rdf-store = { workspace = true }
aruna-sparql = { workspace = true }
aruna-shacl = { workspace = true }
aruna-repl = { workspace = true }
aruna-search = { workspace = true }
aruna-sync = { workspace = true }
aruna-rocrate = { workspace = true }
oxrdf = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tempfile = { workspace = true }
proptest = { workspace = true }
